#!/bin/sh
# SPDX-License-Identifier: GPL-2.0-or-later

echo 'nameserver 1.1.1.1' >> /etc/resolv.conf
export FEX_HOSTFEATURES=enableavx
export FEX_SMALLTSCSCALE=false
unset WAYLAND_DISPLAY
exec FEXInterpreter /usr/bin/steam "${@}"
